const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.argv[2];
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw new Error('Browser tests require loopback');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:390,height:844}});
  const calls=[],external=[],errors=[];
  let status='waiting', needsNickname=false, explanation=null, questionMode='quiz',pollChecks=0;
  const pollCheck=(ok,message)=>{assert(ok,message);pollChecks++;};
  const q=()=>({title:'Která odpověď je správná?',status,session_id:10,lecture_slug:'lesson',question_slug:'question',subject_slug:'subject',options:[{index:0,code:'A',label:'První odpověď',count:1,percent:100}],gamification:{enabled:needsNickname,join_nickname_required:needsNickname},share_url:base+'/q/lesson/question'});
  await context.route('**/*',async route=>{
    const url=new URL(route.request().url());
    if(url.origin!==base){external.push(url.origin);return route.abort();}
    if(!url.pathname.startsWith('/test-api/'))return route.continue();
    calls.push({path:url.pathname,method:route.request().method()});
    let payload=q();
    if(url.pathname.endsWith('/join'))payload={question:q()};
    if(url.pathname.endsWith('/current'))payload={...q(),question_slug:['joining','open'].includes(status)?'question':null};
    if(url.pathname.includes('/results/'))payload={...q(),total:1,mode:questionMode,correct_answer_explanation:explanation,correct_index:questionMode==='poll'?0:null,overall_leaderboard:questionMode==='poll'?[{nickname:'Earlier quiz',points:900,correct_count:1,answers:1}]:[],question_leaderboard:questionMode==='poll'?[{nickname:'Unexpected poll ranking',points:900,is_correct:true,option_index:0,response_ms:100}]:[],participant_result:{points:900,is_correct:true,option_code:'A',hall_of_fame:{enabled:true,eligible:true,visibility:'unset',rank:1,limit:10}}};
    if(url.pathname.includes('/projection/'))payload={status:'waiting',subject_title:'Testovací předmět'};
    await route.fulfill({json:payload});
  });
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/q/lesson/question');
  await page.getByText('Počkejte, až vyučující spustí hlasování.',{exact:false}).waitFor();
  assert(!calls.some(x=>x.path.endsWith('/activate')),'Student landing activated live question');
  status='open';
  await page.getByRole('button',{name:'A První odpověď'}).waitFor({timeout:8000});
  await page.getByText('▦ Sdílet připojení').click();
  assert.equal(await page.locator('[data-qr-ready="1"] canvas').count(),1,'Local QR must be generated');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile page overflows');
  fs.mkdirSync(path.resolve('runtime/screenshots'),{recursive:true});
  await page.screenshot({path:path.resolve('runtime/screenshots/student-live.png'),fullPage:true});
  // Regression: status changes while the question and session IDs stay the same.
  status='joining';
  await page.reload();
  await page.getByText('Připojují se studenti…',{exact:true}).waitFor();
  await page.waitForTimeout(2700);
  status='open';
  await page.getByRole('button',{name:'A První odpověď'}).waitFor({timeout:8000});
  assert.equal(await page.locator('.option').count(),1,'Same-session status transition not rendered');
  // Both nickname entry and returning with a stored nickname remain read-only control.
  status='waiting';needsNickname=true;
  await page.reload();
  await page.getByLabel('Přezdívka',{exact:true}).waitFor();
  await page.waitForTimeout(300);
  await page.getByLabel('Přezdívka',{exact:true}).fill('Testující');
  await page.getByRole('button',{name:'Pokračovat k hlasování'}).click();
  await page.getByText('Počkejte, až vyučující spustí hlasování.',{exact:false}).waitFor();
  await page.reload();
  await page.getByText('Počkejte, až vyučující spustí hlasování.',{exact:false}).waitFor();
  assert(!calls.some(x=>x.path.endsWith('/activate')),'Nickname entry/return activated live question');
  status='closed';
  await page.evaluate(()=>localStorage.setItem('mhl_voted_10','1'));
  await page.reload();
  await page.getByRole('button',{name:'Přidat mou přezdívku'}).click();
  await page.getByText('Přezdívka byla přidána do Síně slávy.').waitFor();
  await page.getByRole('button',{name:'Zůstat anonymní'}).click();
  await page.getByText('V Síni slávy zůstanete anonymní.').waitFor();
  assert.equal(calls.filter(x=>x.path.endsWith('/privacy/hall-opt-in')).length,2,'Hall buttons did not call API');
  explanation='<img src=x onerror=alert(1)> Bezpečné vysvětlení.\nDruhý řádek.';
  await page.reload();
  await page.locator('.answer-explanation').waitFor();
  assert((await page.locator('.answer-explanation').innerText()).includes(explanation),'Feedback text must remain literal');
  assert.equal(await page.locator('.answer-explanation img').count(),0,'Explanation cannot execute markup');
  await page.screenshot({path:path.resolve('runtime/screenshots/student-feedback.png'),fullPage:true});
  await page.goto(base+'/r/lesson/question');
  await page.locator('.answer-explanation').waitFor();
  status='open'; await page.reload(); await page.locator('.waiting-results').waitFor();
  assert.equal(await page.locator('.answer-explanation').count(),0,'Open question cannot display injected feedback');
  status='closed'; questionMode='poll'; await page.reload(); await page.locator('.results-head').waitFor();
  assert.equal(await page.locator('.answer-explanation').count(),0,'Poll cannot display quiz explanation');
  pollCheck(await page.locator('.result-bar-card.correct').count()===0,'Poll never colors a correct answer, even with stale payload fields');
  pollCheck(!(await page.locator('#mhl-app').textContent()).includes('Unexpected poll ranking'),'Projection omits a poll question ranking');
  pollCheck((await page.locator('.leaderboard-note').textContent()).includes('předchozích soutěžních otázek'),'Projection explains the previous score');
  await page.goto(base+'/q/lesson/question');
  await page.locator('.student-result').waitFor();
  pollCheck(await page.locator('.student-good,.student-bad,.score-strip').count()===0,'Poll participant sees no correctness or points');
  pollCheck(await page.locator('.hall-qualify,.question-ranking').count()===0,'Poll does not offer ranking or Hall qualification');
  pollCheck((await page.locator('.student-result').innerText()).includes('Vaše odpověď'),'Poll identifies the chosen answer neutrally');
  pollCheck(!(await page.locator('.student-result').innerText()).includes('Čas od STARTU'),'Poll answer does not imply speed scoring');
  pollCheck((await page.locator('.leaderboard-note').textContent()).includes('Tato anketa body nepřidává'),'Student sees why the previous quiz ranking remains');

  await page.goto(base+'/project/subject/abc123');
  await page.getByRole('heading',{name:'Čekáme na další otázku'}).waitFor();
  assert(calls.some(x=>x.path==='/test-api/projection/subject/abc123'),'Projection used wrong API path');
  assert(!calls.some(x=>x.path.includes('/projection/')&&x.path.endsWith('/current')));
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base+'/demo/');
  await page.getByRole('heading',{name:'Vyzkoušejte si hlasování tak, jak ho uvidí studenti.'}).waitFor();
  await page.waitForTimeout(1000);
  await page.screenshot({path:path.resolve('runtime/screenshots/demo-intro.png'),fullPage:true});
  assert.equal(external.length,0,'Local test attempted external request: '+external);
  assert.deepEqual(errors,[],'Browser runtime errors');
  await browser.close();
  console.log(JSON.stringify({status:'passed',checks:15+pollChecks,neutral_poll_checks:pollChecks,screenshots:3,backend:'synthetic HTTP fixtures; demo PHP real',external_requests:external.length}));
})().catch(e=>{console.error(e);process.exit(1);});
